pipeline {
    agent any

    stages {
        stage('Show Workspace') {
            steps {
                bat 'cd'
                bat 'dir'
                bat 'dir streamlit-app'
            }
        }
    }
}