pipeline {
    agent any

    environment {
        EC2_HOST = '13.203.226.182'
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('streamlit-app') {
                    bat 'python -m pip install -r requirements.txt'
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(credentials: ['aws-ec2-key']) {
                    bat '''
                    ssh -o StrictHostKeyChecking=no ubuntu@%EC2_HOST% ^
                    "cd /home/ubuntu/Dynamic-Inventory-Manager && \
                    git pull origin main && \
                    pkill -f streamlit || true && \
                    cd streamlit-app && \
                    source venv/bin/activate && \
                    nohup streamlit run app.py --server.address 0.0.0.0 --server.port 8501 > streamlit.log 2>&1 &"
                    '''
                }
            }
        }
    }
}