pipeline {
    agent any

    environment {
        EC2_HOST = '13.203.226.182'
    }

stage('Deploy to EC2') {
    steps {
        bat """
        ssh -i C:/Users/dell/Downloads/Aishwarya@2005.pem -o StrictHostKeyChecking=no ubuntu@13.203.226.182 "cd /home/ubuntu/Dynamic-Inventory-Manager && git pull origin main && pkill -f streamlit || true && cd streamlit-app && source venv/bin/activate && nohup streamlit run app.py --server.address 0.0.0.0 --server.port 8501 > streamlit.log 2>&1 &"
        """
    }
}
    }
}